# Form implementation generated from reading ui file '.\ui\dlg_rat.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_DlgRat(object):
    def setupUi(self, DlgRat):
        DlgRat.setObjectName("DlgRat")
        DlgRat.resize(400, 146)
        self.gridLayout_2 = QtWidgets.QGridLayout(DlgRat)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelNameRat = QtWidgets.QLabel(parent=DlgRat)
        self.labelNameRat.setObjectName("labelNameRat")
        self.gridLayout.addWidget(self.labelNameRat, 0, 0, 1, 1)
        self.lineEditNameRat = QtWidgets.QLineEdit(parent=DlgRat)
        self.lineEditNameRat.setObjectName("lineEditNameRat")
        self.gridLayout.addWidget(self.lineEditNameRat, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.pushButtonAdd = QtWidgets.QPushButton(parent=DlgRat)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.gridLayout_2.addWidget(self.pushButtonAdd, 1, 0, 1, 1)

        self.retranslateUi(DlgRat)
        QtCore.QMetaObject.connectSlotsByName(DlgRat)

    def retranslateUi(self, DlgRat):
        _translate = QtCore.QCoreApplication.translate
        DlgRat.setWindowTitle(_translate("DlgRat", "Dialog"))
        self.labelNameRat.setText(_translate("DlgRat", "Name"))
        self.pushButtonAdd.setText(_translate("DlgRat", "Add"))
