# Form implementation generated from reading ui file '.\ui\dlg_device.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_DlgDevice(object):
    def setupUi(self, DlgDevice):
        DlgDevice.setObjectName("DlgDevice")
        DlgDevice.resize(337, 211)
        self.gridLayout_2 = QtWidgets.QGridLayout(DlgDevice)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelSerialDevice = QtWidgets.QLabel(parent=DlgDevice)
        self.labelSerialDevice.setObjectName("labelSerialDevice")
        self.gridLayout.addWidget(self.labelSerialDevice, 1, 0, 1, 1)
        self.lineEditSerialDevice = QtWidgets.QLineEdit(parent=DlgDevice)
        self.lineEditSerialDevice.setObjectName("lineEditSerialDevice")
        self.gridLayout.addWidget(self.lineEditSerialDevice, 1, 2, 1, 1)
        self.lineEditNameDevice = QtWidgets.QLineEdit(parent=DlgDevice)
        self.lineEditNameDevice.setObjectName("lineEditNameDevice")
        self.gridLayout.addWidget(self.lineEditNameDevice, 0, 2, 1, 1)
        self.labelNameDevice = QtWidgets.QLabel(parent=DlgDevice)
        self.labelNameDevice.setObjectName("labelNameDevice")
        self.gridLayout.addWidget(self.labelNameDevice, 0, 0, 1, 1)
        self.labelModelDevice = QtWidgets.QLabel(parent=DlgDevice)
        self.labelModelDevice.setObjectName("labelModelDevice")
        self.gridLayout.addWidget(self.labelModelDevice, 2, 0, 1, 1)
        self.lineEditModelDevice = QtWidgets.QLineEdit(parent=DlgDevice)
        self.lineEditModelDevice.setObjectName("lineEditModelDevice")
        self.gridLayout.addWidget(self.lineEditModelDevice, 2, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=DlgDevice)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)

        self.retranslateUi(DlgDevice)
        QtCore.QMetaObject.connectSlotsByName(DlgDevice)

    def retranslateUi(self, DlgDevice):
        _translate = QtCore.QCoreApplication.translate
        DlgDevice.setWindowTitle(_translate("DlgDevice", "Dialog"))
        self.labelSerialDevice.setText(_translate("DlgDevice", "Serial"))
        self.labelNameDevice.setText(_translate("DlgDevice", "Name"))
        self.labelModelDevice.setText(_translate("DlgDevice", "Model"))
        self.pushButton.setText(_translate("DlgDevice", "Add"))
