# Form implementation generated from reading ui file '.\ui\v1\wdt_monitor.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_FormMonitor(object):
    def setupUi(self, FormMonitor):
        FormMonitor.setObjectName("FormMonitor")
        FormMonitor.resize(579, 353)
        self.gridLayout = QtWidgets.QGridLayout(FormMonitor)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayoutMonitor = QtWidgets.QVBoxLayout()
        self.verticalLayoutMonitor.setObjectName("verticalLayoutMonitor")
        self.gridLayout.addLayout(self.verticalLayoutMonitor, 0, 0, 1, 1)

        self.retranslateUi(FormMonitor)
        QtCore.QMetaObject.connectSlotsByName(FormMonitor)

    def retranslateUi(self, FormMonitor):
        _translate = QtCore.QCoreApplication.translate
        FormMonitor.setWindowTitle(_translate("FormMonitor", "Мониторинг"))
