# Form implementation generated from reading ui file '.\ui\dlg_schedule.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_DialogSchedule(object):
    def setupUi(self, DialogSchedule):
        DialogSchedule.setObjectName("DialogSchedule")
        DialogSchedule.resize(411, 217)
        self.gridLayout_2 = QtWidgets.QGridLayout(DialogSchedule)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelDevices = QtWidgets.QLabel(parent=DialogSchedule)
        self.labelDevices.setObjectName("labelDevices")
        self.gridLayout.addWidget(self.labelDevices, 0, 0, 1, 1)
        self.labelRecordingRepeatTime = QtWidgets.QLabel(parent=DialogSchedule)
        self.labelRecordingRepeatTime.setObjectName("labelRecordingRepeatTime")
        self.gridLayout.addWidget(self.labelRecordingRepeatTime, 3, 0, 1, 1)
        self.labelRats = QtWidgets.QLabel(parent=DialogSchedule)
        self.labelRats.setObjectName("labelRats")
        self.gridLayout.addWidget(self.labelRats, 1, 0, 1, 1)
        self.labelRecordingDuration = QtWidgets.QLabel(parent=DialogSchedule)
        self.labelRecordingDuration.setObjectName("labelRecordingDuration")
        self.gridLayout.addWidget(self.labelRecordingDuration, 2, 0, 1, 1)
        self.comboBoxDevices = QtWidgets.QComboBox(parent=DialogSchedule)
        self.comboBoxDevices.setObjectName("comboBoxDevices")
        self.gridLayout.addWidget(self.comboBoxDevices, 0, 1, 1, 1)
        self.comboBoxRats = QtWidgets.QComboBox(parent=DialogSchedule)
        self.comboBoxRats.setObjectName("comboBoxRats")
        self.gridLayout.addWidget(self.comboBoxRats, 1, 1, 1, 1)
        self.lineEditRecordingDuration = QtWidgets.QLineEdit(parent=DialogSchedule)
        self.lineEditRecordingDuration.setObjectName("lineEditRecordingDuration")
        self.gridLayout.addWidget(self.lineEditRecordingDuration, 2, 1, 1, 1)
        self.lineEditRecordingRepeatTime = QtWidgets.QLineEdit(parent=DialogSchedule)
        self.lineEditRecordingRepeatTime.setObjectName("lineEditRecordingRepeatTime")
        self.gridLayout.addWidget(self.lineEditRecordingRepeatTime, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.pushButtonCreateTask = QtWidgets.QPushButton(parent=DialogSchedule)
        self.pushButtonCreateTask.setObjectName("pushButtonCreateTask")
        self.gridLayout_2.addWidget(self.pushButtonCreateTask, 1, 0, 1, 1)

        self.retranslateUi(DialogSchedule)
        QtCore.QMetaObject.connectSlotsByName(DialogSchedule)

    def retranslateUi(self, DialogSchedule):
        _translate = QtCore.QCoreApplication.translate
        DialogSchedule.setWindowTitle(_translate("DialogSchedule", "Create schedule"))
        self.labelDevices.setText(_translate("DialogSchedule", "Devices"))
        self.labelRecordingRepeatTime.setText(_translate("DialogSchedule", "Recording repeat time, sec"))
        self.labelRats.setText(_translate("DialogSchedule", "Rats"))
        self.labelRecordingDuration.setText(_translate("DialogSchedule", "Recording duration, sec"))
        self.pushButtonCreateTask.setText(_translate("DialogSchedule", "Add"))
